= Resume
Aaron Dorheim-Davis
:toc:

== About Me

I am *Aaron Dorheim-Davis*, a software developer living in Seattle, WA. For the
past 7 years, I have gained experience in a range of technology and in a variety
of industries. Most of my work experience has been focused on C#, ASP.NET (both
Webforms and MVC), utilizing either a SQL Server or Oracle backend. Much of this
work has also involved integration between the company's application and the
customer's other systems.

While my work has been primarily on the Microsoft stack, I often use a personal
projects to learn other languages and technology. The programming languages I
have studied include PHP, VB, Haskell, Ruby and Python, plus a bit of OCaml and
Scala. Of those, Python is the what I'm most comfortable with. I am interested
in DevOps and am currently learning Vagrant.

I am currently looking for a job inside the Seattle city limits, on the bus
lines, and preferably in one of the following neighborhoods: Ballard, Fremont,
Downtown, Pioneer Square or Belltown. Alternatively, I am also interested in
working remotely.

<<<

== Work History

=== Wizards of the Coast
May 2013 -> Present (contract)

|===
|Perforce |SQL Server  |Visual Studio |jQuery
|===

.Software Developer
- Helped develop and launch the New Wizards Account System
- Worked on PlanesWalkerPoints.com, a leaderboard site for players of Magic the
  Gathering, written in .NET MVC
- Utilized JQuery for front end javascript
- Worked on a few internal-facing sites written in a combination of ASP.NET
  Webforms and MVC
- Developed and consumed WCF based webservices
- Worked on several internal tools written in WPF

=== MCG Health, LLC (formerly _Milliman Care Guidelines_)
October 2011 -> May 2013

|===
| Subversion | Visual Studio | SQL Server |Oracle |PowerShell
|===

.Software Development Engineer
- Worked on the development team of the flagship product, including as the sole
  developer for a customer preview site of new functionality
- Utilized Agile / Scrum style development practices in a small team, supported
  by a White Board and TFS for work item tracking, and TFS for source
  control. Prior to transitioning to TFS, we used Subversion for source control.
- Developed Sql Server and Oracle versions of the database, in both clean and
  upgrade installation scenarios.
- Developed a Powershell module to simplify our existing process of creationg /
  upgrading the databases on dev boxes, and for switching between multiple
  environments.

=== Ventyx, an ABB Company (formerly _Insert Key Solutions, Inc._)
November 2006 -> October 2011

|===
|Visual Studio |SQL Server |Oracle
|===

.Software Developer / Analyst
- Gathered and analyzed requirements from customers
- Developed web applications in ASP.NET Web Forms
- Developed Sql Server and Oracle based backends
- Created installation / upgrade scripts, and performed installation in customer
  environments.
- Spearheaded an effort to develop and utilize a set of in-house libraries
  (responsibility later transferred to another developer)
- Agile development, using Visual Studio 2010 and Team Foundation Server
  integration for maintenance of source code and issue tracking.
- Loaded legacy data from customer sources, typically Excel spreadsheets and
  Access databases
- Development of intregration procedures for communication between our
  applications and the customers' other systems

=== Exelon Business Services Company
July 2006 -> November 2006 (contract)

|===
| MS Access | SQL Server
|===

.SQL Query Analyzer
- Analysed disparate, legacy data sources (typically Excel spreadsheets and
  Access databases), and loaded that data into a new, centralized database.
